#!/usr/bin/env ruby

require 'rubygems'
require 'pp'

require './lib/ajson/scanner'
require './lib/ajson/parser'

content = STDIN.read

tokens = AJSON::Scanner.new(content).scan
ast = AJSON::Parser.new.parse(tokens)

pp ast

