#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'
module AJSON
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 58)

   def parse(tokens)
      @tokens = tokens

      do_parse
   end

   def next_token
      @tokens.shift
   end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     7,    12,    13,    14,    15,     4,    26,     7,    27,     5,
    22,     7,    12,    13,    14,    15,     4,    30,    28,    29,
     5,     7,    12,    13,    14,    15,     4,     7,     4,     6,
     5,    25,     5,     8 ]

racc_action_check = [
     5,     5,     5,     5,     5,     5,     9,    27,     9,     5,
     5,    28,    28,    28,    28,    28,    28,    23,    10,    23,
    28,    30,    30,    30,    30,    30,    30,     4,     0,     1,
    30,     6,     0,     4 ]

racc_action_pointer = [
    21,    29,   nil,   nil,    25,    -2,    31,   nil,   nil,    -2,
     9,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     7,   nil,   nil,   nil,     5,     9,   nil,
    19,   nil,   nil,   nil ]

racc_action_default = [
   -23,   -23,    -6,    -7,   -23,   -23,   -23,    -1,   -14,   -23,
   -23,   -17,    -2,    -3,    -4,    -5,    -8,    -9,   -10,   -11,
   -12,   -13,   -19,   -23,   -21,    34,   -15,   -23,   -23,   -20,
   -23,   -18,   -16,   -22 ]

racc_goto_table = [
    24,    10,     1,    11,     3,     9,     2,    23,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    32,    10,    33,    31 ]

racc_goto_check = [
     8,     2,     1,    10,     7,     9,     6,    11,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     8,     2,     8,    10 ]

racc_goto_pointer = [
   nil,     2,    -3,   nil,   nil,   nil,     6,     4,    -5,     1,
    -1,     2 ]

racc_goto_default = [
   nil,   nil,    18,    19,    17,    16,    20,    21,   nil,   nil,
   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 15, :_reduce_1,
  1, 16, :_reduce_2,
  1, 17, :_reduce_3,
  1, 17, :_reduce_4,
  1, 18, :_reduce_5,
  1, 14, :_reduce_none,
  1, 14, :_reduce_none,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  2, 19, :_reduce_14,
  3, 19, :_reduce_15,
  3, 23, :_reduce_16,
  1, 22, :_reduce_17,
  3, 22, :_reduce_18,
  2, 20, :_reduce_19,
  3, 20, :_reduce_20,
  1, 24, :_reduce_21,
  3, 24, :_reduce_22 ]

racc_reduce_n = 23

racc_shift_n = 34

racc_token_table = {
  false => 0,
  :error => 1,
  :STRING => 2,
  :NUMBER => 3,
  :TRUE => 4,
  :FALSE => 5,
  :NULL => 6,
  "{" => 7,
  "}" => 8,
  ":" => 9,
  "," => 10,
  "[" => 11,
  "]" => 12 }

racc_nt_base = 13

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "STRING",
  "NUMBER",
  "TRUE",
  "FALSE",
  "NULL",
  "\"{\"",
  "\"}\"",
  "\":\"",
  "\",\"",
  "\"[\"",
  "\"]\"",
  "$start",
  "JSONText",
  "JSONString",
  "JSONNumber",
  "JSONBooleanLiteral",
  "JSONNullLiteral",
  "JSONObject",
  "JSONArray",
  "JSONValue",
  "JSONMemberList",
  "JSONMember",
  "JSONElementList" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 6)
  def _reduce_1(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 8)
  def _reduce_2(val, _values, result)
     result = val[0].to_f 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 10)
  def _reduce_3(val, _values, result)
     result = true 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 10)
  def _reduce_4(val, _values, result)
     result = false 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 12)
  def _reduce_5(val, _values, result)
     result = nil 
    result
  end
.,.,

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

module_eval(<<'.,.,', 'parser.y', 20)
  def _reduce_14(val, _values, result)
          result = {}
   
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 23)
  def _reduce_15(val, _values, result)
          result = val[1].inject({}) do |r, s|
         r.merge!({s[0] => s[1]})
      end
   
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 28)
  def _reduce_16(val, _values, result)
     result = [val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 32)
  def _reduce_17(val, _values, result)
          result = [val[0]]
   
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 35)
  def _reduce_18(val, _values, result)
          val[0].push(val[2])
   
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 40)
  def _reduce_19(val, _values, result)
          result = []
   
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 43)
  def _reduce_20(val, _values, result)
          result = val[1]
   
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 48)
  def _reduce_21(val, _values, result)
          result = [val[0]]
   
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 51)
  def _reduce_22(val, _values, result)
          val[0].push(val[2])
   
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module AJSON
